// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1KKj4f69JJkT8Vka5cOiCaIL07I8sqJI',
    appId: '1:748141669409:web:fa94b35eafd41b726ec760',
    messagingSenderId: '748141669409',
    projectId: 'kottanchoru-93b5c',
    authDomain: 'kottanchoru-93b5c.firebaseapp.com',
    storageBucket: 'kottanchoru-93b5c.firebasestorage.app',
    measurementId: 'G-G9PK0R2CVN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhmqlgXCndhMCfo1PXMDkyL09ioKtlBks',
    appId: '1:748141669409:android:8c8cf18441bcf7846ec760',
    messagingSenderId: '748141669409',
    projectId: 'kottanchoru-93b5c',
    storageBucket: 'kottanchoru-93b5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIpfoGvC2Ke8ooFQWFXHURUYwZD5bHYB8',
    appId: '1:748141669409:ios:8e2ac92cc200c80f6ec760',
    messagingSenderId: '748141669409',
    projectId: 'kottanchoru-93b5c',
    storageBucket: 'kottanchoru-93b5c.firebasestorage.app',
    iosBundleId: 'com.example.kottanchoru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIpfoGvC2Ke8ooFQWFXHURUYwZD5bHYB8',
    appId: '1:748141669409:ios:8e2ac92cc200c80f6ec760',
    messagingSenderId: '748141669409',
    projectId: 'kottanchoru-93b5c',
    storageBucket: 'kottanchoru-93b5c.firebasestorage.app',
    iosBundleId: 'com.example.kottanchoru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1KKj4f69JJkT8Vka5cOiCaIL07I8sqJI',
    appId: '1:748141669409:web:05609623d52a1cb76ec760',
    messagingSenderId: '748141669409',
    projectId: 'kottanchoru-93b5c',
    authDomain: 'kottanchoru-93b5c.firebaseapp.com',
    storageBucket: 'kottanchoru-93b5c.firebasestorage.app',
    measurementId: 'G-SBYY0D16GS',
  );

}